nav:
    - README: index.md
    - Reference:
          - Command: reference/command.md
          - CompletedCommand: reference/completed-command.md
          - CommandError: reference/command-error.md
site_name: tshu
repo_url: https://github.com/aspizu/tshu
repo_name: tshu
site_author: Priyanshu Dangare
site_url: https://aspizu.github.io/tshu
theme:
    name: material
    features:
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - navigation.instant.preview
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - content.code.annotate
        - toc.follow
        - navigation.path
        - navigation.top
        - content.code.copy
        - content.tabs.link
    font:
        text: Inter Tight
        code: Cascadia Code
plugins:
    - search
    - mkdocstrings:
          handlers:
              python:
                  options:
                      show_source: false
                      show_symbol_type_heading: true
                      merge_init_into_class: true
                      parameter_headings: true
                      show_signature_annotations: true
markdown_extensions:
    - admonition
    - pymdownx.highlight:
          default_lang: python
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/aspizu
        - icon: fontawesome/brands/discord
          link: https://discord.gg/MMfMkRuhAf
